services:
  backend:
    build: ./backend
    container_name: cv-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: cvuser
      DB_PASSWORD: cvpass
      DB_NAME: cvsite
      PORT: 5000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: cv-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: cv-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cvpass
      MYSQL_DATABASE: cvsite
      MYSQL_USER: cvuser
      MYSQL_PASSWORD: cvpass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: